spring:
  datasource:
    url: jdbc:mysql://192.168.1.111:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: changhyeon
    password: tyzm4060!
    driver-class-name: org.mariadb.jdbc.Driver

server:
  servlet:
    jsp:
      init-parameters:
        development: true

api:
  key:
  confmKey: devU01TX0FVVEgyMDIzMDQxMTA5MDUzNjExMzY3NDI=


